// Copyright (c) 2025 hotflow2024
// Licensed under AGPL-3.0-or-later. See LICENSE for details.
// Commercial licensing available. See COMMERCIAL_LICENSE.md.
/**
 * Director Store
 * Manages AI screenplay generation and scene execution state
 */

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { createProjectScopedStorage } from '@/lib/project-storage';
import { DEFAULT_CINEMATOGRAPHY_PROFILE_ID } from '@/lib/constants/cinematography-profiles';
import type { 
  AIScreenplay, 
  AIScene, 
  SceneProgress, 
  GenerationConfig 
} from '@opencut/ai-core';
import type {
  LightingStyle,
  LightingDirection,
  ColorTemperature,
  DepthOfField,
  FocusTransition,
  CameraRig,
  MovementSpeed,
  AtmosphericEffect,
  EffectIntensity,
  PlaybackSpeed,
  ContinuityRef,
  CameraAngle,
  FocalLength,
  PhotographyTechnique,
} from '@/types/script';

// ==================== Types ====================

export type ScreenplayStatus = 'idle' | 'generating' | 'ready' | 'generating_images' | 'images_ready' | 'generating_videos' | 'completed' | 'error';

// Storyboard-specific status
export type StoryboardStatus = 'idle' | 'generating' | 'preview' | 'splitting' | 'editing' | 'error';

// Generation status for each scene (used for both image and video)
export type GenerationStatus = 'idle' | 'uploading' | 'generating' | 'completed' | 'failed';
// Alias for backward compatibility
export type VideoStatus = GenerationStatus;

// ==================== Preset Constants (Imported from director-presets.ts and re-exported) ====================
// Local imports: Used for type references in this file (required for SplitScene interface definition)
import type {
  ShotSizeType,
  DurationType,
  SoundEffectTag,
  EmotionTag,
} from './director-presets';
// Re-export: Maintains backward compatibility for existing imports (e.g., import { SHOT_SIZE_PRESETS } from '@/stores/director-store')
export {
  SHOT_SIZE_PRESETS,
  type ShotSizeType,
  DURATION_PRESETS,
  type DurationType,
  SOUND_EFFECT_PRESETS,
  type SoundEffectTag,
  LIGHTING_STYLE_PRESETS,
  LIGHTING_DIRECTION_PRESETS,
  COLOR_TEMPERATURE_PRESETS,
  DEPTH_OF_FIELD_PRESETS,
  FOCUS_TRANSITION_PRESETS,
  CAMERA_RIG_PRESETS,
  MOVEMENT_SPEED_PRESETS,
  ATMOSPHERIC_EFFECT_PRESETS,
  EFFECT_INTENSITY_PRESETS,
  PLAYBACK_SPEED_PRESETS,
  EMOTION_PRESETS,
  type EmotionTag,
  CAMERA_ANGLE_PRESETS,
  type CameraAngleType,
  FOCAL_LENGTH_PRESETS,
  type FocalLengthType,
  PHOTOGRAPHY_TECHNIQUE_PRESETS,
  type PhotographyTechniqueType,
  CAMERA_MOVEMENT_PRESETS,
  type CameraMovementType,
  SPECIAL_TECHNIQUE_PRESETS,
  type SpecialTechniqueType,
} from './director-presets';

// Split Scene (Formerly Storyboard):
// Three-tier prompt design:
// 1. Initial Frame Prompt (imagePrompt) - Static scene description for generating the first frame image
// 2. End Frame Prompt (endFramePrompt) - Static scene description for generating the end frame image (if needed)
// 3. Video Prompt (videoPrompt) - Dynamic motion description for generating the video
export interface SplitScene {
  id: number;
  // Scene Name (e.g., Mountain Village School)
  sceneName: string;
  // Scene Location (e.g., Inside Classroom)
  sceneLocation: string;
  
  // ========== First Frame (Start State) ==========
  // First frame image (cut from storyboard or generated by AI)
  imageDataUrl: string;
  // HTTP URL of the first frame image (for video generation API)
  imageHttpUrl: string | null;
  width: number;
  height: number;
  // First frame image prompt (English, for image generation API)
  // Focus: composition, lighting, character appearance, starting pose (static description)
  imagePrompt: string;
  // First frame image prompt (Chinese, for display and editing)
  imagePromptZh: string;
  // First frame generation status
  imageStatus: GenerationStatus;
  imageProgress: number; // 0-100
  imageError: string | null;
  
  // ========== End Frame (End State) ==========
  // Whether an end frame is needed (automatically determined by AI or manually set by user)
  // Scenes needing end frames: large displacements, transformations, large camera shifts, transitions, stylized videos
  // Scenes not needing end frames: simple dialogues, micro-motions, open scenes
  needsEndFrame: boolean;
  // End frame image URL (data URL or local path)
  endFrameImageUrl: string | null;
  // HTTP URL of the end frame image (for visual continuity in video generation API)
  endFrameHttpUrl: string | null;
  // End frame source: null=none | upload=user upload | ai-generated=AI generated | next-scene=next scene first frame | video-extracted=extracted from video | prev-scene-cascade=previous scene frame cascade
  endFrameSource: 'upload' | 'ai-generated' | 'next-scene' | 'video-extracted' | 'prev-scene-cascade' | null;
  // End frame image prompt (English, for image generation API)
  // Focus: ending pose, state after position change (static description)
  endFramePrompt: string;
  // End frame image prompt (Chinese, for display and editing)
  endFramePromptZh: string;
  // End frame generation status
  endFrameStatus: GenerationStatus;
  endFrameProgress: number; // 0-100
  endFrameError: string | null;
  
  // ========== Video Movement ==========
  // Video movement prompt (English, for video generation API)
  // Focus: action process, camera movement, atmospheric changes (dynamic description)
  // Note: Detailed character appearance is not needed as the initial frame exists
  videoPrompt: string;
  // Video movement prompt (Chinese, for display and editing)
  videoPromptZh: string;
  // Video generation status
  videoStatus: GenerationStatus;
  videoProgress: number; // 0-100
  videoUrl: string | null;
  videoError: string | null;
  // Media library reference (for dragging to timeline)
  videoMediaId: string | null;
  
  // ========== Characters & Emotions ==========
  // Character library selection (for character consistency during video generation)
  characterIds: string[];
  // Character wardrobe variation mapping (charId -> variationId, defaults to base fixed photo)
  characterVariationMap?: Record<string, string>;
  // Emotion tags (ordered, for video atmosphere and tone control)
  emotionTags: EmotionTag[];
  
  // ========== Script Import Info (Reference Only) ==========
  // Dialogue (for voiceover and subtitles)
  dialogue: string;
  // Action Summary (imported from script, for reference)
  actionSummary: string;
  // Camera Movement Description (Dolly In, Pan Right, Static, etc.)
  cameraMovement: string;
  // Sound Effect Text Description (imported from script)
  soundEffectText: string;
  
  // ========== Video Parameters ==========
  // Shot Size Type (affects visual prompt)
  shotSize: ShotSizeType | null;
  // Video Duration (API parameter: 5s or 10s)
  duration: DurationType;
  // Ambient Sound (merged into prompt)
  ambientSound: string;
  // Sound Effect Tags (merged into prompt) - Legacy field, kept for compatibility
  soundEffects: SoundEffectTag[];
  
  // ========== Audio Switches (Controls whether to merge into video generation prompt) ==========
  audioAmbientEnabled?: boolean;   // Ambient sound switch, default true
  audioSfxEnabled?: boolean;       // Sound effects switch, default true
  audioDialogueEnabled?: boolean;  // Dialogue switch, default true
  audioBgmEnabled?: boolean;       // BGM switch, default false (disabled)
  backgroundMusic?: string;        // Background music description text
  
  // ========== Grid Position Info ==========
  row: number;
  col: number;
  sourceRect: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  
  // ========== Scene Library Mapping (for reference images) ==========
  // First frame scene mapping
  sceneLibraryId?: string;           // Scene library ID
  viewpointId?: string;              // Viewpoint ID (e.g., 'sofa', 'dining')
  subViewId?: string;                // Sub-view ID for quad-grid (e.g., 'front', 'back')
  sceneReferenceImage?: string;      // Scene background reference image URL
  
  // End frame scene mapping (may differ from first frame)
  endFrameSceneLibraryId?: string;   // End frame scene library ID
  endFrameViewpointId?: string;      // End frame viewpoint ID
  endFrameSubViewId?: string;        // End frame sub-view ID
  endFrameSceneReferenceImage?: string; // End frame scene background reference image URL
  
  // ========== Narrative-Driven Design (Based on "The Grammar of Film Language") ==========
  narrativeFunction?: string;        // Narrative function: Setup/Upgrade/Climax/Turning Point/Transition/Outro
  shotPurpose?: string;              // Shot purpose: Why this shot is used
  visualFocus?: string;              // Visual focus: What the audience should see (in order)
  cameraPosition?: string;           // Camera position: Camera position relative to characters
  characterBlocking?: string;        // Character blocking: Positional relationship of characters in the frame
  rhythm?: string;                   // Rhythm description: The rhythm feel of this shot
  visualDescription?: string;        // Detailed visual description
  
  // ========== Gaffer (Lighting) — Independent for each scene ==========
  lightingStyle?: LightingStyle;           // Lighting style
  lightingDirection?: LightingDirection;   // Main light source direction
  colorTemperature?: ColorTemperature;     // Color temperature
  lightingNotes?: string;                  // Lighting supplementary notes
  
  // ========== Focus Puller — Independent for each scene ==========
  depthOfField?: DepthOfField;             // Depth of field
  focusTarget?: string;                    // Focus target: "Character face" / "Letter on table"
  focusTransition?: FocusTransition;       // Focus transition action
  
  // ========== Camera Rig — Independent for each scene ==========
  cameraRig?: CameraRig;                   // Camera rig type
  movementSpeed?: MovementSpeed;           // Movement speed
  
  // ========== On-set SFX — Independent for each scene ==========
  atmosphericEffects?: AtmosphericEffect[]; // Atmospheric effects (multi-select)
  effectIntensity?: EffectIntensity;       // Effect intensity
  
  // ========== Speed Ramping — Independent for each scene ==========
  playbackSpeed?: PlaybackSpeed;           // Playback speed
  
  // ========== Camera Angle / Focal Length / Photography Technique — Independent for each scene ==========
  cameraAngle?: CameraAngle;               // Camera angle
  focalLength?: FocalLength;               // Lens focal length
  photographyTechnique?: PhotographyTechnique; // Photography technique
  
  // ========== Special Camera Techniques — Independent for each scene ==========
  specialTechnique?: string;               // Special techniques (Dolly zoom, Bullet time, etc.)
  
  // ========== Continuity — Independent for each scene ==========
  continuityRef?: ContinuityRef;           // Continuity reference
  
  // Image source: 'ai-generated' | 'upload' | 'storyboard'
  imageSource?: 'ai-generated' | 'upload' | 'storyboard';
  
// ========== Episode Sources ==========
sourceEpisodeIndex?: number;   // Source episode index
sourceEpisodeId?: string;      // Source episode ID

// ========== Angle Switching History Records ==========
// Start frame angle switching history
startFrameAngleSwitchHistory?: Array<{
  imageUrl: string;
  angleLabel: string;
  timestamp: number;
}>;
// End frame angle switching history
endFrameAngleSwitchHistory?: Array<{
  imageUrl: string;
  angleLabel: string;
  timestamp: number;
}>;
}

// Trailer duration type (seconds)
export type TrailerDuration = 10 | 30 | 60;

// Trailer configuration
export interface TrailerConfig {
  duration: TrailerDuration;  // Seconds
  shotIds: string[];          // List of selected scene IDs (referencing Shot IDs in screenplay)
  generatedAt?: number;       // Generation time
  status: 'idle' | 'generating' | 'completed' | 'error';
  error?: string;
}

export interface DirectorScreenplayDraft {
  prompt: string;
  selectedCharacterIds: string[];
  updatedAt: number;
}

export interface DirectorEditorPrefs {
  imageGenMode: 'single' | 'merged';
  frameMode: 'first' | 'last' | 'both';
  refStrategy: 'cluster' | 'minimal' | 'none';
  useExemplar: boolean;
  activeTab: 'editing' | 'trailer';
  episodeViewScope: 'all' | 'episode';
}

// Per-project director data
export interface DirectorProjectData {
  // Storyboard state (new workflow)
  storyboardImage: string | null;
  storyboardImageMediaId: string | null;
  storyboardStatus: StoryboardStatus;
  storyboardError: string | null;
  splitScenes: SplitScene[];
  projectFolderId: string | null;
  storyboardConfig: {
    aspectRatio: '16:9' | '9:16';
    resolution: '2K' | '4K' | '1K';
    videoResolution: '480p' | '720p' | '1080p';
    sceneCount: number;
    storyPrompt: string;
    /** Directly stored visual style preset ID (e.g., '2d_ghibli'), used for precise reverse lookup */
    visualStyleId?: string;
    /** Calibrated style ID corresponding to current storyboard data (used to determine if re-calibration is needed when switching styles) */
    calibratedStyleId?: string;
    styleTokens?: string[];
    characterReferenceImages?: string[];
    characterDescriptions?: string[];
  };
  // Legacy screenplay (for backward compatibility)
  screenplay: AIScreenplay | null;
  screenplayStatus: ScreenplayStatus;
  screenplayError: string | null;
  
  // ========== Trailer Features ==========
  trailerConfig: TrailerConfig;
  trailerScenes: SplitScene[];  // List of storyboard scenes specifically for trailer editing
  
  // ========== Cinematography Profile (Project Level) ==========
  cinematographyProfileId?: string;   // Selected cinematography profile preset ID (e.g., 'film-noir')
  screenplayDraft: DirectorScreenplayDraft;
  editorPrefs: DirectorEditorPrefs;
}

interface DirectorState {
  // Active project tracking
  activeProjectId: string | null;
  
  // Per-project data storage
  projects: Record<string, DirectorProjectData>;
  
  // Scene progress map (sceneId -> progress) - transient, not persisted
  sceneProgress: Map<number, SceneProgress>;
  
  // Generation config - global
  config: GenerationConfig;
  
  // UI state - global
  isExpanded: boolean;
  selectedSceneId: number | null;
}

interface DirectorActions {
  // Project management
  setActiveProjectId: (projectId: string | null) => void;
  ensureProject: (projectId: string) => void;
  getProjectData: (projectId: string) => DirectorProjectData;
  
  // Screenplay management
  setScreenplay: (screenplay: AIScreenplay | null) => void;
  setScreenplayStatus: (status: ScreenplayStatus) => void;
  setScreenplayError: (error: string | null) => void;
  
  // Scene editing
  updateScene: (sceneId: number, updates: Partial<AIScene>) => void;
  deleteScene: (sceneId: number) => void;
  deleteAllScenes: () => void;
  
  // Scene progress
  updateSceneProgress: (sceneId: number, progress: Partial<SceneProgress>) => void;
  setSceneProgress: (sceneId: number, progress: SceneProgress) => void;
  clearSceneProgress: () => void;
  
  // Config
  updateConfig: (config: Partial<GenerationConfig>) => void;
  
  // UI
  setExpanded: (expanded: boolean) => void;
  setSelectedScene: (sceneId: number | null) => void;
  
  // Storyboard actions (new workflow)
  setStoryboardImage: (imageUrl: string | null, mediaId?: string | null) => void;
  setStoryboardStatus: (status: StoryboardStatus) => void;
  setStoryboardError: (error: string | null) => void;
  setProjectFolderId: (folderId: string | null) => void;
  setSplitScenes: (scenes: SplitScene[]) => void;
  
  // Update initial frame prompt (static scene description)
  updateSplitSceneImagePrompt: (sceneId: number, prompt: string, promptZh?: string) => void;
  // Update video prompt (action process description)
  updateSplitSceneVideoPrompt: (sceneId: number, prompt: string, promptZh?: string) => void;
  // Update end frame prompt (static scene description)
  updateSplitSceneEndFramePrompt: (sceneId: number, prompt: string, promptZh?: string) => void;
  // Set whether an end frame is needed
  updateSplitSceneNeedsEndFrame: (sceneId: number, needsEndFrame: boolean) => void;
  // Legacy API compatibility: update video prompt (actually updates videoPrompt)
  updateSplitScenePrompt: (sceneId: number, prompt: string, promptZh?: string) => void;
  
  updateSplitSceneImage: (sceneId: number, imageDataUrl: string, width?: number, height?: number, httpUrl?: string) => void;
  updateSplitSceneImageStatus: (sceneId: number, updates: Partial<Pick<SplitScene, 'imageStatus' | 'imageProgress' | 'imageError'>>) => void;
  updateSplitSceneVideo: (sceneId: number, updates: Partial<Pick<SplitScene, 'videoStatus' | 'videoProgress' | 'videoUrl' | 'videoError' | 'videoMediaId'>>) => void;
  // End frame image upload/update
  updateSplitSceneEndFrame: (sceneId: number, imageUrl: string | null, source?: 'upload' | 'ai-generated' | 'next-scene' | 'video-extracted' | 'prev-scene-cascade', httpUrl?: string | null) => void;
  // End frame generation status update
  updateSplitSceneEndFrameStatus: (sceneId: number, updates: Partial<Pick<SplitScene, 'endFrameStatus' | 'endFrameProgress' | 'endFrameError'>>) => void;
  // Character library and emotion tag update methods
  updateSplitSceneCharacters: (sceneId: number, characterIds: string[]) => void;
  updateSplitSceneCharacterVariationMap: (sceneId: number, characterVariationMap: Record<string, string>) => void;
  updateSplitSceneEmotions: (sceneId: number, emotionTags: EmotionTag[]) => void;
  // Shot size, duration, ambient sound, and sound effect update methods
  updateSplitSceneShotSize: (sceneId: number, shotSize: ShotSizeType | null) => void;
  updateSplitSceneDuration: (sceneId: number, duration: DurationType) => void;
  updateSplitSceneAmbientSound: (sceneId: number, ambientSound: string) => void;
  updateSplitSceneSoundEffects: (sceneId: number, soundEffects: SoundEffectTag[]) => void;
// Scene library mapping update methods
  updateSplitSceneReference: (sceneId: number, sceneLibraryId?: string, viewpointId?: string, referenceImage?: string, subViewId?: string) => void;
  updateSplitSceneEndFrameReference: (sceneId: number, sceneLibraryId?: string, viewpointId?: string, referenceImage?: string, subViewId?: string) => void;
  // Generic field update method (using SplitScene field)
  updateSplitSceneField: (sceneId: number, field: keyof SplitScene, value: any) => void;
  // Viewpoint switch history record
  addAngleSwitchHistory: (sceneId: number, type: 'start' | 'end', historyItem: { imageUrl: string; angleLabel: string; timestamp: number }) => void;
  deleteSplitScene: (sceneId: number) => void;
  addBlankSplitScene: () => void;
  setStoryboardConfig: (config: Partial<DirectorProjectData['storyboardConfig']>) => void;
  setScreenplayDraft: (draft: Partial<DirectorScreenplayDraft>) => void;
  clearScreenplayDraft: () => void;
  setEditorPrefs: (prefs: Partial<DirectorEditorPrefs>) => void;
  resetStoryboard: () => void;
  
  // Mode 2: Add scenes from script directly (skip storyboard generation)
  addScenesFromScript: (scenes: Array<{
    promptZh: string;
    promptEn?: string;
    // Three-tier prompt system (Seedance 1.5 Pro)
    imagePrompt?: string;      // Initial frame prompt (English)
    imagePromptZh?: string;    // Initial frame prompt (Chinese)
    videoPrompt?: string;      // Video prompt (English)
    videoPromptZh?: string;    // Video prompt (Chinese)
    endFramePrompt?: string;   // End frame prompt (English)
    endFramePromptZh?: string; // End frame prompt (Chinese)
    needsEndFrame?: boolean;   // Whether end frame is needed
    characterIds?: string[];
    emotionTags?: EmotionTag[];
    shotSize?: ShotSizeType | null;
    duration?: number;
    ambientSound?: string;
    soundEffects?: SoundEffectTag[];
    soundEffectText?: string;
    dialogue?: string;
    actionSummary?: string;
    cameraMovement?: string;
    sceneName?: string;
    sceneLocation?: string;
    // Location of the scene clip on the storyboard?
    sceneLibraryId?: string;
    viewpointId?: string;
    sceneReferenceImage?: string;
    // Narrative-Driven Design (Based on "The Grammar of Film Language")
    narrativeFunction?: string;
    shotPurpose?: string;
    visualFocus?: string;
    cameraPosition?: string;
    characterBlocking?: string;
    rhythm?: string;
    visualDescription?: string;
    // Shooting controls (Lighting / Focus / Rig / SFX / Speed) — Independent for each scene
  lightingStyle?: LightingStyle;
    lightingDirection?: LightingDirection;
    colorTemperature?: ColorTemperature;
    lightingNotes?: string;
    depthOfField?: DepthOfField;
    focusTarget?: string;
    focusTransition?: FocusTransition;
    cameraRig?: CameraRig;
    movementSpeed?: MovementSpeed;
    atmosphericEffects?: AtmosphericEffect[];
    effectIntensity?: EffectIntensity;
    playbackSpeed?: PlaybackSpeed;
    // Aperture / Shutter Speed / ISO?
    cameraAngle?: CameraAngle;
    focalLength?: FocalLength;
    photographyTechnique?: PhotographyTechnique;
    // 鐗规畩鎷嶆憚鎵嬫硶
    specialTechnique?: string;
    // 闆嗕綔鐢ㄥ煙
    sourceEpisodeIndex?: number;
    sourceEpisodeId?: string;
  }>) => void;
  
  // Workflow actions (these will trigger worker commands)
  startScreenplayGeneration: (prompt: string, images?: File[]) => void;
  startImageGeneration: () => void;      // Step 1: Generate images only
  startVideoGeneration: () => void;      // Step 2: Generate videos from images
  retrySceneImage: (sceneId: number) => void;  // Retry single scene image
  retryScene: (sceneId: number) => void;
  cancelAll: () => void;
  reset: () => void;
  
  // Worker callbacks (called by WorkerBridge)
  onScreenplayGenerated: (screenplay: AIScreenplay) => void;
  onSceneProgressUpdate: (sceneId: number, progress: SceneProgress) => void;
  onSceneImageCompleted: (sceneId: number, imageUrl: string) => void;  // Image only
  onSceneCompleted: (sceneId: number, mediaId: string) => void;         // Video completed
  onSceneFailed: (sceneId: number, error: string) => void;
  onAllImagesCompleted: () => void;   // All images done, ready for review
  onAllCompleted: () => void;          // All videos done
  
  // ========== Trailer Features ==========
  setTrailerDuration: (duration: TrailerDuration) => void;
  setTrailerScenes: (scenes: SplitScene[]) => void;
  setTrailerConfig: (config: Partial<TrailerConfig>) => void;
  clearTrailer: () => void;
  
  // ========== 鎽勫奖椋庢牸妗ｆ ==========
  setCinematographyProfileId: (profileId: string | undefined) => void;
  
  // ========== 瑙嗛鎴抚鈫掗甯х骇鑱旇縼绉?==========
  cascadeFramesToNextScene: (params: {
    nextSceneId: number;
    // Original first frame -> end frame
    origFirstFrameImage: string;
    origFirstFrameHttpUrl: string | null;
    origFirstFramePrompt: string;
    origFirstFramePromptZh: string;
    // Video extracted frame -> new first frame
    newFirstFrameImage: string;
    newFirstFrameHttpUrl: string | null;
    newFirstFramePrompt: string;
    newFirstFramePromptZh: string;
  }) => void;
}

type DirectorStore = DirectorState & DirectorActions;

// ==================== Default Config ====================

const defaultConfig: GenerationConfig = {
  styleTokens: ['anime style', 'manga art', '2D animation', 'cel shaded'],
  qualityTokens: ['high quality', 'detailed', 'professional'],
  negativePrompt: 'blurry, low quality, watermark, realistic, photorealistic, 3D render',
  aspectRatio: '9:16',
  imageSize: '1K',
  videoSize: '480p',
  sceneCount: 5,
  concurrency: 1,
  imageProvider: 'memefast',
  videoProvider: 'memefast',
  chatProvider: 'memefast',
};

// ==================== Default Project Data ====================

const defaultProjectData = (): DirectorProjectData => ({
  storyboardImage: null,
  storyboardImageMediaId: null,
  storyboardStatus: 'editing',
  storyboardError: null,
  splitScenes: [],
  projectFolderId: null,
  storyboardConfig: {
    aspectRatio: '9:16',
    resolution: '2K',
    videoResolution: '480p',
    sceneCount: 5,
    storyPrompt: '',
    styleTokens: [],
    characterReferenceImages: [],
    characterDescriptions: [],
  },
  screenplay: null,
  screenplayStatus: 'idle',
  screenplayError: null,
  // Trailer default values
  trailerConfig: {
    duration: 30,
    shotIds: [],
    status: 'idle',
  },
  trailerScenes: [],
  // Cinematography profile: Using classic film cinematography as the default base
  cinematographyProfileId: DEFAULT_CINEMATOGRAPHY_PROFILE_ID,
  screenplayDraft: {
    prompt: '',
    selectedCharacterIds: [],
    updatedAt: 0,
  },
  editorPrefs: {
    imageGenMode: 'merged',
    frameMode: 'first',
    refStrategy: 'cluster',
    useExemplar: true,
    activeTab: 'editing',
    episodeViewScope: 'episode',
  },
});

const defaultScreenplayDraft: DirectorScreenplayDraft = {
  prompt: '',
  selectedCharacterIds: [],
  updatedAt: 0,
};

const defaultEditorPrefs: DirectorEditorPrefs = {
  imageGenMode: 'merged',
  frameMode: 'first',
  refStrategy: 'cluster',
  useExemplar: true,
  activeTab: 'editing',
  episodeViewScope: 'episode',
};

const normalizeDirectorProjectData = (project: any): DirectorProjectData => {
  const defaults = defaultProjectData();
  return {
    ...defaults,
    ...project,
    storyboardConfig: {
      ...defaults.storyboardConfig,
      ...(project?.storyboardConfig || {}),
    },
    trailerConfig: {
      ...defaults.trailerConfig,
      ...(project?.trailerConfig || {}),
    },
    screenplayDraft: {
      ...defaultScreenplayDraft,
      ...(project?.screenplayDraft || {}),
    },
    editorPrefs: {
      ...defaultEditorPrefs,
      ...(project?.editorPrefs || {}),
    },
  };
};

// ==================== Initial State ====================

const initialState: DirectorState = {
  activeProjectId: null,
  projects: {},
  sceneProgress: new Map(),
  config: defaultConfig,
  isExpanded: true,
  selectedSceneId: null,
};

// ==================== Store ====================

// Helper to get current project data
const getCurrentProject = (state: DirectorState): DirectorProjectData | null => {
  if (!state.activeProjectId) return null;
  return state.projects[state.activeProjectId] || null;
};

export const useDirectorStore = create<DirectorStore>()(
  persist(
    (set, get) => ({
      ...initialState,

  // Project management
  setActiveProjectId: (projectId) => {
    set({ activeProjectId: projectId });
    if (projectId) {
      get().ensureProject(projectId);
    }
  },
  
  ensureProject: (projectId) => {
    const { projects } = get();
    if (projects[projectId]) return;
    set({
      projects: { ...projects, [projectId]: defaultProjectData() },
    });
  },
  
  getProjectData: (projectId) => {
    const { projects } = get();
    return projects[projectId] || defaultProjectData();
  },

  // Screenplay management
  setScreenplay: (screenplay) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          screenplay,
          screenplayError: null,
        },
      },
    });
  },
  
  setScreenplayStatus: (status) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          screenplayStatus: status,
        },
      },
    });
  },
  
  setScreenplayError: (error) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const currentProject = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...currentProject,
          screenplayError: error,
          screenplayStatus: error ? 'error' : currentProject?.screenplayStatus || 'idle',
        },
      },
    });
  },

  // Scene editing
  updateScene: (sceneId, updates) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    if (!project?.screenplay) return;
    
    const updatedScenes = project.screenplay.scenes.map(scene => 
      scene.sceneId === sceneId ? { ...scene, ...updates } : scene
    );
    
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          screenplay: {
            ...project.screenplay,
            scenes: updatedScenes,
            updatedAt: Date.now(),
          },
        },
      },
    });
  },
  
  // Delete a single scene
  deleteScene: (sceneId) => {
    const { activeProjectId, projects, sceneProgress } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    if (!project?.screenplay) return;
    
    const remainingScenes = project.screenplay.scenes.filter(scene => scene.sceneId !== sceneId);
    const renumberedScenes = remainingScenes.map((scene, index) => ({
      ...scene,
      sceneId: index + 1,
    }));
    
    const newProgressMap = new Map<number, SceneProgress>();
    remainingScenes.forEach((scene, index) => {
      const oldProgress = sceneProgress.get(scene.sceneId);
      if (oldProgress) {
        newProgressMap.set(index + 1, { ...oldProgress, sceneId: index + 1 });
      }
    });
    
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          screenplay: {
            ...project.screenplay,
            scenes: renumberedScenes,
            updatedAt: Date.now(),
          },
        },
      },
      sceneProgress: newProgressMap,
    });
    
    console.log('[DirectorStore] Deleted scene', sceneId, 'remaining:', renumberedScenes.length);
  },
  
  // Delete all scenes and reset to idle
  deleteAllScenes: () => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          screenplay: null,
          screenplayStatus: 'idle',
          screenplayError: null,
        },
      },
      sceneProgress: new Map(),
      selectedSceneId: null,
    });
    console.log('[DirectorStore] Deleted all scenes, reset to idle');
  },

  // Scene progress
  updateSceneProgress: (sceneId, partialProgress) => {
    const current = get().sceneProgress.get(sceneId);
    const updated = current 
      ? { ...current, ...partialProgress }
      : { 
          sceneId, 
          status: 'pending' as const, 
          stage: 'idle' as const, 
          progress: 0, 
          ...partialProgress 
        };
    
    set((state) => {
      const newMap = new Map(state.sceneProgress);
      newMap.set(sceneId, updated);
      return { sceneProgress: newMap };
    });
  },
  
  setSceneProgress: (sceneId, progress) => {
    set((state) => {
      const newMap = new Map(state.sceneProgress);
      newMap.set(sceneId, progress);
      return { sceneProgress: newMap };
    });
  },
  
  clearSceneProgress: () => set({ sceneProgress: new Map() }),

  // Config
  updateConfig: (partialConfig) => set((state) => ({
    config: { ...state.config, ...partialConfig }
  })),

  // UI
  setExpanded: (expanded) => set({ isExpanded: expanded }),
  setSelectedScene: (sceneId) => set({ selectedSceneId: sceneId }),

  // Storyboard actions (new workflow) - Project-aware
  setStoryboardImage: (imageUrl, mediaId) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          storyboardImage: imageUrl,
          storyboardImageMediaId: mediaId ?? null,
        },
      },
    });
  },
  
  setStoryboardStatus: (status) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          storyboardStatus: status,
        },
      },
    });
  },
  
  setProjectFolderId: (folderId) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          projectFolderId: folderId,
        },
      },
    });
  },
  
  setStoryboardError: (error) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const currentProject = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...currentProject,
          storyboardError: error,
          storyboardStatus: error ? 'error' : currentProject?.storyboardStatus || 'idle',
        },
      },
    });
  },
  
  setSplitScenes: (scenes) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    
    // Ensure all scenes have all fields initialized with defaults
    const initialized = scenes.map(s => ({
      ...s,
      // Basic scene information
      sceneName: (s as any).sceneName ?? '',
      sceneLocation: (s as any).sceneLocation ?? '',
      
      // ========== Initial Frame Related ==========
      imageHttpUrl: (s as any).imageHttpUrl ?? null,
      // Initial frame prompt (new)
      imagePrompt: (s as any).imagePrompt ?? s.videoPrompt ?? '',
      imagePromptZh: (s as any).imagePromptZh ?? s.videoPromptZh ?? s.videoPrompt ?? '',
      // Initial frame generation status
      imageStatus: s.imageStatus || 'completed' as const,
      imageProgress: s.imageProgress ?? 100,
      imageError: s.imageError ?? null,
      
      // ========== 灏惧抚鐩稿叧 ==========
// Whether an end frame is needed (automatically determined by AI or manually set by user)
// Scenes needing end frames: large displacements, transformations, large camera shifts, transitions, stylized videos
// Scenes not needing end frames: simple dialogues, micro-motions, open scenes
needsEndFrame: (s as any).needsEndFrame ?? false,
      endFrameImageUrl: s.endFrameImageUrl ?? null,
      endFrameHttpUrl: (s as any).endFrameHttpUrl ?? null,
      endFrameSource: s.endFrameSource ?? null,
      // 灏惧抚鎻愮ず璇嶏紙鏂板锛?
      endFramePrompt: (s as any).endFramePrompt ?? '',
      endFramePromptZh: (s as any).endFramePromptZh ?? '',
      // 灏惧抚鐢熸垚鐘舵€侊紙鏂板锛?
      endFrameStatus: (s as any).endFrameStatus || 'idle' as const,
      endFrameProgress: (s as any).endFrameProgress ?? 0,
      endFrameError: (s as any).endFrameError ?? null,
      
      // ========== Video Related ==========
      videoPromptZh: s.videoPromptZh ?? s.videoPrompt ?? '',
      videoStatus: s.videoStatus || 'idle' as const,
      videoProgress: s.videoProgress ?? 0,
      videoUrl: s.videoUrl ?? null,
      videoError: s.videoError ?? null,
      videoMediaId: s.videoMediaId ?? null,
      
      // ========== 瑙掕壊涓庢儏缁?==========
      characterIds: s.characterIds ?? [],
      emotionTags: s.emotionTags ?? [],
      
      // ========== Script Import Info ==========
      dialogue: s.dialogue ?? '',
      actionSummary: s.actionSummary ?? '',
      cameraMovement: s.cameraMovement ?? '',
      soundEffectText: (s as any).soundEffectText ?? '',
      
      // ========== Video Parameters ==========
      shotSize: s.shotSize ?? null,
      duration: s.duration ?? 5,
      ambientSound: s.ambientSound ?? '',
      soundEffects: s.soundEffects ?? [],
      
      // ========== Gaffer (Lighting) — Independent for each scene ==========
      lightingStyle: s.lightingStyle ?? undefined,
      lightingDirection: s.lightingDirection ?? undefined,
      colorTemperature: s.colorTemperature ?? undefined,
      lightingNotes: s.lightingNotes ?? undefined,
      
      // ========== Focus Puller — Independent for each scene ==========
      depthOfField: s.depthOfField ?? undefined,
      focusTarget: s.focusTarget ?? undefined,
      focusTransition: s.focusTransition ?? undefined,
      
      // ========== Camera Rig — Independent for each scene ==========
      cameraRig: s.cameraRig ?? undefined,
      movementSpeed: s.movementSpeed ?? undefined,
      
      // ========== On-set SFX — Independent for each scene ==========
      atmosphericEffects: s.atmosphericEffects ?? undefined,
      effectIntensity: s.effectIntensity ?? undefined,
      
      // ========== Speed Ramping — Independent for each scene ==========
      playbackSpeed: s.playbackSpeed ?? undefined,
      
      // ========== Special Camera Techniques — Independent for each scene ==========
      specialTechnique: s.specialTechnique ?? undefined,
      
      // ========== Continuity — Independent for each scene ==========
      continuityRef: s.continuityRef ?? undefined,
    }));
    
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          splitScenes: initialized,
        },
      },
    });
  },
  
  // ========== Three-Tier Prompt Update Methods ==========
  
  // Update initial frame prompt (static scene description)
  updateSplitSceneImagePrompt: (sceneId, prompt, promptZh) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { 
        ...scene, 
        imagePrompt: prompt,
        imagePromptZh: promptZh !== undefined ? promptZh : scene.imagePromptZh,
      } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },
  
  // Update video prompt (action process description)
  updateSplitSceneVideoPrompt: (sceneId, prompt, promptZh) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { 
        ...scene, 
        videoPrompt: prompt,
        videoPromptZh: promptZh !== undefined ? promptZh : scene.videoPromptZh,
      } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },
  
  // Update end frame prompt (static scene description)
  updateSplitSceneEndFramePrompt: (sceneId, prompt, promptZh) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { 
        ...scene, 
        endFramePrompt: prompt,
        endFramePromptZh: promptZh !== undefined ? promptZh : scene.endFramePromptZh,
      } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },
  
  // Set whether an end frame is needed
  updateSplitSceneNeedsEndFrame: (sceneId, needsEndFrame) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, needsEndFrame } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },
  
  // Legacy API compatibility: update video prompt (actually updates videoPrompt)
  updateSplitScenePrompt: (sceneId, prompt, promptZh) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { 
        ...scene, 
        videoPrompt: prompt,
        videoPromptZh: promptZh !== undefined ? promptZh : scene.videoPromptZh,
      } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  // 鏇存柊鍒嗛暅鍥剧墖
  // 娉ㄦ剰锛氬綋鍥剧墖鍙樺寲鏃讹紝濡傛灉娌℃湁浼犲叆鏂扮殑 httpUrl锛屽簲璇ユ竻闄ゆ棫鐨?httpUrl
  // 杩欐牱鍙互閬垮厤鐢ㄦ埛浠庣礌鏉愬簱閫夋嫨鏂板浘鐗囧悗锛屾棫鐨?HTTP URL 浠嶇劧琚娇鐢?
  // 鍏抽敭锛氬悓鏃舵竻闄?imageSource锛岄伩鍏嶈棰戠敓鎴愭椂閿欒鍦颁娇鐢ㄦ棫鐨?imageHttpUrl
  updateSplitSceneImage: (sceneId, imageDataUrl, width, height, httpUrl) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { 
        ...scene, 
        imageDataUrl,
        // 濡傛灉鏄惧紡浼犲叆 httpUrl锛堝寘鎷┖瀛楃涓诧級锛屼娇鐢ㄥ畠锛涘惁鍒欒缃负 null 寮哄埗娓呴櫎
        // 浣跨敤 null 鑰屼笉鏄?undefined锛岀‘淇濊鐩栨棫鍊?
        imageHttpUrl: httpUrl !== undefined ? (httpUrl || null) : null,
        // 濡傛灉娌℃湁浼犲叆 httpUrl锛屾竻闄?imageSource 鏍囪锛岄伩鍏嶈棰戠敓鎴愭椂璇垽
        imageSource: httpUrl ? 'ai-generated' : undefined,
        imageStatus: 'completed' as const,
        imageProgress: 100,
        imageError: null,
        ...(width !== undefined && { width }),
        ...(height !== undefined && { height }),
      } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneImageStatus: (sceneId, updates) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, ...updates } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneVideo: (sceneId, updates) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, ...updates } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  // Update end frame image (supports multiple sources)
  // Note: When end frame changes, if no new httpUrl is provided, the old httpUrl should be cleared
  updateSplitSceneEndFrame: (sceneId, imageUrl, source, httpUrl) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { 
        ...scene, 
        endFrameImageUrl: imageUrl,
        // 濡傛灉鏄惧紡浼犲叆 httpUrl锛屼娇鐢ㄥ畠锛涘惁鍒欐竻绌猴紙鍥犱负灏惧抚宸插彉鍖栨垨鍒犻櫎锛?
        endFrameHttpUrl: httpUrl !== undefined ? (httpUrl || null) : null,
        endFrameSource: imageUrl ? (source || 'upload') : null,
        endFrameStatus: imageUrl ? 'completed' as const : 'idle' as const,
        endFrameProgress: imageUrl ? 100 : 0,
        endFrameError: null,
      } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },
  
  // Update end frame generation status
  updateSplitSceneEndFrameStatus: (sceneId, updates) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, ...updates } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneCharacters: (sceneId, characterIds) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, characterIds } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneCharacterVariationMap: (sceneId, characterVariationMap) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, characterVariationMap } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneEmotions: (sceneId, emotionTags) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, emotionTags } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneShotSize: (sceneId, shotSize) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, shotSize } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneDuration: (sceneId, duration) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, duration } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneAmbientSound: (sceneId, ambientSound) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, ambientSound } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  updateSplitSceneSoundEffects: (sceneId, soundEffects) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, soundEffects } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },

  // Scene library mapping update method (initial frame)
  updateSplitSceneReference: (sceneId, sceneLibraryId, viewpointId, referenceImage, subViewId) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId
        ? { ...scene, sceneLibraryId, viewpointId, subViewId, sceneReferenceImage: referenceImage }
        : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
    console.log('[DirectorStore] Updated scene reference for shot', sceneId, ':', sceneLibraryId, viewpointId, subViewId);
  },

  // Scene library mapping update method (end frame)
  updateSplitSceneEndFrameReference: (sceneId, sceneLibraryId, viewpointId, referenceImage, subViewId) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId
        ? { ...scene, endFrameSceneLibraryId: sceneLibraryId, endFrameViewpointId: viewpointId, endFrameSubViewId: subViewId, endFrameSceneReferenceImage: referenceImage }
        : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
    console.log('[DirectorStore] Updated end frame scene reference for shot', sceneId, ':', sceneLibraryId, viewpointId, subViewId);
  },

// Generic field update method (using SplitScene field)
  updateSplitSceneField: (sceneId, field, value) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene =>
      scene.id === sceneId ? { ...scene, [field]: value } : scene
    );
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },
  
  // Viewpoint switch history record update method
  addAngleSwitchHistory: (sceneId, type, historyItem) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const updated = project.splitScenes.map(scene => {
      if (scene.id !== sceneId) return scene;
      if (type === 'start') {
        const history = scene.startFrameAngleSwitchHistory || [];
        return { ...scene, startFrameAngleSwitchHistory: [...history, historyItem] };
      } else {
        const history = scene.endFrameAngleSwitchHistory || [];
        return { ...scene, endFrameAngleSwitchHistory: [...history, historyItem] };
      }
    });
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
  },
  
  deleteSplitScene: (sceneId) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const remaining = project.splitScenes.filter(s => s.id !== sceneId);
    const renumbered = remaining.map((s, idx) => ({ ...s, id: idx }));
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: renumbered },
      },
    });
    console.log('[DirectorStore] Deleted split scene', sceneId, 'remaining:', renumbered.length);
  },
  
  setStoryboardConfig: (partialConfig) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          storyboardConfig: { ...project.storyboardConfig, ...partialConfig },
        },
      },
    });
  },

  setScreenplayDraft: (partialDraft) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          screenplayDraft: {
            ...(project.screenplayDraft || defaultScreenplayDraft),
            ...partialDraft,
            updatedAt: Date.now(),
          },
        },
      },
    });
  },

  clearScreenplayDraft: () => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          screenplayDraft: {
            ...defaultScreenplayDraft,
            updatedAt: Date.now(),
          },
        },
      },
    });
  },

  setEditorPrefs: (partialPrefs) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          editorPrefs: {
            ...(project.editorPrefs || defaultEditorPrefs),
            ...partialPrefs,
          },
        },
      },
    });
  },
  
  resetStoryboard: () => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          storyboardImage: null,
          storyboardImageMediaId: null,
          storyboardStatus: 'editing',
          storyboardError: null,
          splitScenes: [],
        },
      },
    });
    console.log('[DirectorStore] Reset storyboard state for project', activeProjectId);
  },

  // Mode 2: Add scenes from script directly (skip storyboard, generate images individually)
  addScenesFromScript: (scenes) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const splitScenes = project?.splitScenes || [];
    const startId = splitScenes.length > 0 ? Math.max(...splitScenes.map(s => s.id)) + 1 : 0;
    
    const newScenes: SplitScene[] = scenes.map((scene, index) => ({
      id: startId + index,
      sceneName: scene.sceneName || '',
      sceneLocation: scene.sceneLocation || '',
      imageDataUrl: '',
      imageHttpUrl: null,
      width: 0,
      height: 0,
      // Three-tier prompt system: prioritize specific prompt fields, fallback to legacy promptEn/promptZh
      imagePrompt: scene.imagePrompt || scene.promptEn || '',
      imagePromptZh: scene.imagePromptZh || scene.promptZh || '',
      videoPrompt: scene.videoPrompt || scene.promptEn || '',
      videoPromptZh: scene.videoPromptZh || scene.promptZh,
      endFramePrompt: scene.endFramePrompt || '',
      endFramePromptZh: scene.endFramePromptZh || '',
      needsEndFrame: scene.needsEndFrame || false,
      row: 0,
      col: 0,
      sourceRect: { x: 0, y: 0, width: 0, height: 0 },
      endFrameImageUrl: null,
      endFrameHttpUrl: null,
      endFrameSource: null,
      endFrameStatus: 'idle' as const,
      endFrameProgress: 0,
      endFrameError: null,
      characterIds: scene.characterIds || [],
      emotionTags: scene.emotionTags || [],
      shotSize: scene.shotSize || null,
      duration: scene.duration || 5,
      ambientSound: scene.ambientSound || '',
      soundEffects: scene.soundEffects || [],
      soundEffectText: scene.soundEffectText || '',
      dialogue: scene.dialogue || '',
      actionSummary: scene.actionSummary || '',
      cameraMovement: scene.cameraMovement || '',
      // Audio switches: all enabled by default (BGM disabled by default)
      audioAmbientEnabled: true,
      audioSfxEnabled: true,
      audioDialogueEnabled: true,
      audioBgmEnabled: false,
      backgroundMusic: scene.backgroundMusic || '',
      // Scene library mapping (automatic matching)
      sceneLibraryId: scene.sceneLibraryId,
      viewpointId: scene.viewpointId,
      sceneReferenceImage: scene.sceneReferenceImage,
      // Narrative-Driven Design (Based on "The Grammar of Film Language")
      narrativeFunction: scene.narrativeFunction || '',
      shotPurpose: scene.shotPurpose || '',
      visualFocus: scene.visualFocus || '',
      cameraPosition: scene.cameraPosition || '',
      characterBlocking: scene.characterBlocking || '',
      rhythm: scene.rhythm || '',
      visualDescription: scene.visualDescription || '',
      // Shooting controls (Lighting/Focus/Rig/SFX/Speed) — Independent for each scene
      lightingStyle: scene.lightingStyle,
      lightingDirection: scene.lightingDirection,
      colorTemperature: scene.colorTemperature,
      lightingNotes: scene.lightingNotes,
      depthOfField: scene.depthOfField,
      focusTarget: scene.focusTarget,
      focusTransition: scene.focusTransition,
      cameraRig: scene.cameraRig,
      movementSpeed: scene.movementSpeed,
      atmosphericEffects: scene.atmosphericEffects,
      effectIntensity: scene.effectIntensity,
      playbackSpeed: scene.playbackSpeed,
      // Special camera techniques
      specialTechnique: scene.specialTechnique,
      // Camera angle / Focal length / Photography technique
      cameraAngle: scene.cameraAngle,
      focalLength: scene.focalLength,
      photographyTechnique: scene.photographyTechnique,
      imageStatus: 'idle' as const,
      imageProgress: 0,
      imageError: null,
      videoStatus: 'idle' as const,
      videoProgress: 0,
      videoUrl: null,
      videoError: null,
      videoMediaId: null,
      // Episode scope
      sourceEpisodeIndex: scene.sourceEpisodeIndex,
      sourceEpisodeId: scene.sourceEpisodeId,
    }));
    
    // Initialize calibratedStyleId to the current visualStyleId (marks calibrated style when adding new scene)
    const currentConfig = project.storyboardConfig;
    const calibratedUpdate = currentConfig.visualStyleId && !currentConfig.calibratedStyleId
      ? { storyboardConfig: { ...currentConfig, calibratedStyleId: currentConfig.visualStyleId } }
      : {};

    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          ...calibratedUpdate,
          splitScenes: [...splitScenes, ...newScenes],
          storyboardStatus: 'editing',
        },
      },
    });
    
    console.log('[DirectorStore] Added', newScenes.length, 'scenes from script, total:', splitScenes.length + newScenes.length);
  },

  // Add blank scene (manually created by user; upload images/fill prompts/generate yourself)
  addBlankSplitScene: () => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const splitScenes = project?.splitScenes || [];
    const newId = splitScenes.length > 0 ? Math.max(...splitScenes.map(s => s.id)) + 1 : 0;

    const blankScene: SplitScene = {
      id: newId,
      sceneName: `Blank Scene ${newId + 1}`,
      sceneLocation: '',
      imageDataUrl: '',
      imageHttpUrl: null,
      width: 0,
      height: 0,
      imagePrompt: '',
      imagePromptZh: '',
      videoPrompt: '',
      videoPromptZh: '',
      endFramePrompt: '',
      endFramePromptZh: '',
      needsEndFrame: false,
      row: 0,
      col: 0,
      sourceRect: { x: 0, y: 0, width: 0, height: 0 },
      endFrameImageUrl: null,
      endFrameHttpUrl: null,
      endFrameSource: null,
      endFrameStatus: 'idle',
      endFrameProgress: 0,
      endFrameError: null,
      characterIds: [],
      emotionTags: [],
      shotSize: null,
      duration: 5,
      ambientSound: '',
      soundEffects: [],
      soundEffectText: '',
      dialogue: '',
      actionSummary: '',
      cameraMovement: '',
      audioAmbientEnabled: true,
      audioSfxEnabled: true,
      audioDialogueEnabled: true,
      audioBgmEnabled: false,
      backgroundMusic: '',
      imageStatus: 'idle',
      imageProgress: 0,
      imageError: null,
      videoStatus: 'idle',
      videoProgress: 0,
      videoUrl: null,
      videoError: null,
      videoMediaId: null,
    };

    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          splitScenes: [...splitScenes, blankScene],
          storyboardStatus: 'editing',
        },
      },
    });

    console.log('[DirectorStore] Added blank scene, id:', newId, 'total:', splitScenes.length + 1);
  },

  // Workflow actions
  startScreenplayGeneration: (prompt, images) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          screenplayStatus: 'generating',
          screenplayError: null,
          screenplay: null,
        },
      },
    });
    
    console.log('[DirectorStore] Starting screenplay generation for:', prompt.substring(0, 50));
  },

  // Step 1: Start generating images only
  startImageGeneration: () => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const screenplay = project?.screenplay;
    if (!screenplay) {
      console.error('[DirectorStore] No screenplay to generate images');
      return;
    }
    
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          screenplayStatus: 'generating_images',
        },
      },
    });
    
    const progressMap = new Map<number, SceneProgress>();
    for (const scene of screenplay.scenes) {
      progressMap.set(scene.sceneId, {
        sceneId: scene.sceneId,
        status: 'pending',
        stage: 'image',
        progress: 0,
      });
    }
    set({ sceneProgress: progressMap });
    
    console.log('[DirectorStore] Starting image generation for', screenplay.scenes.length, 'scenes');
  },
  
  // Step 2: Start generating videos from confirmed images
  startVideoGeneration: () => {
    const { activeProjectId, projects, sceneProgress } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const screenplay = project?.screenplay;
    if (!screenplay) {
      console.error('[DirectorStore] No screenplay to generate videos');
      return;
    }
    
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          screenplayStatus: 'generating_videos',
        },
      },
    });
    
    const progressMap = new Map<number, SceneProgress>();
    for (const scene of screenplay.scenes) {
      const existing = sceneProgress.get(scene.sceneId);
      progressMap.set(scene.sceneId, {
        sceneId: scene.sceneId,
        status: 'pending',
        stage: 'video',
        progress: 50,
        imageUrl: existing?.imageUrl,
      });
    }
    set({ sceneProgress: progressMap });
    
    console.log('[DirectorStore] Starting video generation for', screenplay.scenes.length, 'scenes');
  },
  
  // Retry generating image for a single scene
  retrySceneImage: (sceneId) => {
    get().updateSceneProgress(sceneId, {
      status: 'pending',
      stage: 'image',
      progress: 0,
      imageUrl: undefined,
      error: undefined,
    });
    console.log('[DirectorStore] Retrying image for scene', sceneId);
  },

  retryScene: (sceneId) => {
    get().updateSceneProgress(sceneId, {
      status: 'pending',
      stage: 'idle',
      progress: 0,
      error: undefined,
    });
    console.log('[DirectorStore] Retrying scene', sceneId);
  },

  cancelAll: () => {
    const { activeProjectId, projects, sceneProgress } = get();
    if (activeProjectId) {
      const project = projects[activeProjectId];
      const screenplay = project?.screenplay;
      set({
        projects: {
          ...projects,
          [activeProjectId]: {
            ...project,
            screenplayStatus: screenplay ? 'ready' : 'idle',
          },
        },
      });
    }
    
    for (const [sceneId, progress] of sceneProgress) {
      if (progress.status === 'generating' || progress.status === 'pending') {
        get().updateSceneProgress(sceneId, {
          status: 'failed',
          error: 'Cancelled by user',
        });
      }
    }
    
    console.log('[DirectorStore] Cancelled all operations');
  },

  reset: () => set(initialState),

  // Worker callbacks
  onScreenplayGenerated: (screenplay) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          screenplay,
          screenplayStatus: 'ready',
          screenplayError: null,
        },
      },
    });
    console.log('[DirectorStore] Screenplay generated:', screenplay.title);
  },

  onSceneProgressUpdate: (sceneId, progress) => {
    get().setSceneProgress(sceneId, progress);
  },

  // Called when a scene's image is generated
  onSceneImageCompleted: (sceneId, imageUrl) => {
    get().updateSceneProgress(sceneId, {
      status: 'completed',
      stage: 'image',
      progress: 100,
      imageUrl,
    });
    
    const { activeProjectId, projects, sceneProgress } = get();
    const project = activeProjectId ? projects[activeProjectId] : null;
    const screenplay = project?.screenplay;
    if (screenplay) {
      get().updateScene(sceneId, { imageUrl });
    }
    
    if (screenplay) {
      const allImagesDone = screenplay.scenes.every(scene => {
        const progress = sceneProgress.get(scene.sceneId);
        return progress?.imageUrl || progress?.status === 'failed';
      });
      
      if (allImagesDone) {
        get().onAllImagesCompleted();
      }
    }
    
    console.log('[DirectorStore] Scene image completed:', sceneId, imageUrl?.substring(0, 50));
  },

  onSceneCompleted: (sceneId, mediaId) => {
    get().updateSceneProgress(sceneId, {
      status: 'completed',
      stage: 'done',
      progress: 100,
      mediaId,
      completedAt: Date.now(),
    });
    
    const { activeProjectId, projects, sceneProgress } = get();
    const project = activeProjectId ? projects[activeProjectId] : null;
    const screenplay = project?.screenplay;
    if (screenplay) {
      const allDone = screenplay.scenes.every(scene => {
        const progress = sceneProgress.get(scene.sceneId);
        return progress?.status === 'completed' || progress?.status === 'failed';
      });
      
      if (allDone) {
        get().onAllCompleted();
      }
    }
    
    console.log('[DirectorStore] Scene completed:', sceneId, 'mediaId:', mediaId);
  },

  onSceneFailed: (sceneId, error) => {
    get().updateSceneProgress(sceneId, {
      status: 'failed',
      error,
    });
    console.error('[DirectorStore] Scene failed:', sceneId, error);
  },

  // All images generated, ready for user review
  onAllImagesCompleted: () => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          screenplayStatus: 'images_ready',
        },
      },
    });
    console.log('[DirectorStore] All images completed, ready for review');
  },

  onAllCompleted: () => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...projects[activeProjectId],
          screenplayStatus: 'completed',
        },
      },
    });
    console.log('[DirectorStore] All scenes completed');
  },
  
  // ========== Trailer Feature Implementation ==========
  
  setTrailerDuration: (duration) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          trailerConfig: {
            ...project.trailerConfig,
            duration,
          },
        },
      },
    });
    console.log('[DirectorStore] Trailer duration set to:', duration);
  },
  
  setTrailerScenes: (scenes) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          trailerScenes: scenes,
          trailerConfig: {
            ...project.trailerConfig,
            generatedAt: Date.now(),
            status: 'completed',
          },
        },
      },
    });
    console.log('[DirectorStore] Trailer scenes set:', scenes.length, 'scenes');
  },
  
  setTrailerConfig: (config) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          trailerConfig: {
            ...project.trailerConfig,
            ...config,
          },
        },
      },
    });
    console.log('[DirectorStore] Trailer config updated:', config);
  },
  
  clearTrailer: () => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          trailerConfig: {
            duration: 30,
            shotIds: [],
            status: 'idle',
          },
          trailerScenes: [],
        },
      },
    });
    console.log('[DirectorStore] Trailer cleared');
  },
  
  // ========== 瑙嗛鎴抚鈫掗甯х骇鑱旇縼绉?==========
  
  cascadeFramesToNextScene: (params) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    const {
      nextSceneId,
      origFirstFrameImage,
      origFirstFrameHttpUrl,
      origFirstFramePrompt,
      origFirstFramePromptZh,
      newFirstFrameImage,
      newFirstFrameHttpUrl,
      newFirstFramePrompt,
      newFirstFramePromptZh,
    } = params;
    
    const updated = project.splitScenes.map(scene => {
      if (scene.id !== nextSceneId) return scene;
      
      // Cascade to end frame only if the original initial frame has content
      const hasOrigImage = !!origFirstFrameImage;
      
      // End frame prompt protection: write only when empty
      const endPrompt = scene.endFramePrompt || origFirstFramePrompt;
      const endPromptZh = scene.endFramePromptZh || origFirstFramePromptZh;
      
      // 瑙嗛杩囨湡澶勭悊锛氳嫢宸叉湁瑙嗛锛岄噸缃?
      const videoReset = scene.videoUrl ? {
        videoStatus: 'idle' as const,
        videoProgress: 0,
        videoUrl: null,
        videoError: null,
        videoMediaId: null,
      } : {};
      
      return {
        ...scene,
        // End frame: Migrated from original initial frame
        ...(hasOrigImage ? {
          endFrameImageUrl: origFirstFrameImage,
          endFrameHttpUrl: origFirstFrameHttpUrl,
          endFrameSource: 'prev-scene-cascade' as const,
          endFrameStatus: 'completed' as const,
          endFrameProgress: 100,
          endFrameError: null,
        } : {}),
        endFramePrompt: endPrompt,
        endFramePromptZh: endPromptZh,
        needsEndFrame: true,
        // Initial frame: Video extracted frame
        imageDataUrl: newFirstFrameImage,
        imageHttpUrl: newFirstFrameHttpUrl,
        imagePrompt: newFirstFramePrompt,
        imagePromptZh: newFirstFramePromptZh,
        imageStatus: 'completed' as const,
        imageProgress: 100,
        imageError: null,
        // 瑙嗛杩囨湡閲嶇疆
        ...videoReset,
      };
    });
    
    set({
      projects: {
        ...projects,
        [activeProjectId]: { ...project, splitScenes: updated },
      },
    });
    
    console.log('[DirectorStore] Cascade frames to next scene:', nextSceneId);
  },

  // ========== 鎽勫奖椋庢牸妗ｆ ==========
  
  setCinematographyProfileId: (profileId) => {
    const { activeProjectId, projects } = get();
    if (!activeProjectId) return;
    const project = projects[activeProjectId];
    set({
      projects: {
        ...projects,
        [activeProjectId]: {
          ...project,
          cinematographyProfileId: profileId,
        },
      },
    });
    console.log('[DirectorStore] Cinematography profile set to:', profileId);
  },
    }),
    {
      name: 'moyin-director-store',
      storage: createJSONStorage(() => createProjectScopedStorage('director')),
      partialize: (state) => {
        // Helper: strip base64 data from a string field (keep local-image:// and https://)
        const stripBase64 = (val: string | null | undefined): string | null | undefined => {
          if (!val) return val;
          if (typeof val === 'string' && val.startsWith('data:')) return '';
          return val;
        };

        // Strip base64 from SplitScene to avoid 100MB+ JSON persistence
        const stripScene = (s: SplitScene): SplitScene => ({
          ...s,
          imageDataUrl: (stripBase64(s.imageDataUrl) ?? '') as string,
          endFrameImageUrl: stripBase64(s.endFrameImageUrl) as string | null,
          sceneReferenceImage: stripBase64(s.sceneReferenceImage) as string | undefined,
          endFrameSceneReferenceImage: stripBase64(s.endFrameSceneReferenceImage) as string | undefined,
        });

        const pid = state.activeProjectId;
        
        // Only serialize the active project's data (not all projects)
        let projectData = null;
        if (pid && state.projects[pid]) {
          const proj = state.projects[pid];
          projectData = {
            ...proj,
            storyboardImage: (stripBase64(proj.storyboardImage) ?? null) as string | null,
            splitScenes: proj.splitScenes.map(stripScene),
            trailerScenes: proj.trailerScenes.map(stripScene),
          };
        }

        return {
          activeProjectId: pid,
          projectData,
          config: state.config,
          // Don't persist: sceneProgress (Map), UI state
        };
      },
      merge: (persisted: any, current: any) => {
        if (!persisted) return current;
        
        // Legacy format: has `projects` as Record (from old monolithic file)
        if (persisted.projects && typeof persisted.projects === 'object') {
          const normalizedProjects: Record<string, DirectorProjectData> = {};
          for (const [projectId, projectData] of Object.entries(persisted.projects)) {
            normalizedProjects[projectId] = normalizeDirectorProjectData(projectData);
          }
          return {
            ...current,
            ...persisted,
            projects: normalizedProjects,
          };
        }
        
        // New per-project format: has `projectData` for single project
        const { activeProjectId: pid, projectData, config } = persisted;
        const updates: any = { ...current };
        if (config) updates.config = config;
        if (pid) updates.activeProjectId = pid;
        if (pid && projectData) {
          updates.projects = { ...current.projects, [pid]: normalizeDirectorProjectData(projectData) };
        }
        return updates;
      },
    }
  )
);

// ==================== Selectors ====================

/**
 * Get current active project data (for reading splitScenes, storyboardImage, etc.)
 */
export const useActiveDirectorProject = (): DirectorProjectData | null => {
  return useDirectorStore((state) => {
    if (!state.activeProjectId) return null;
    return state.projects[state.activeProjectId] || null;
  });
};

/**
 * Get progress for a specific scene
 */
export const useSceneProgress = (sceneId: number): SceneProgress | undefined => {
  return useDirectorStore((state) => state.sceneProgress.get(sceneId));
};

/**
 * Get overall progress (0-100)
 */
export const useOverallProgress = (): number => {
  return useDirectorStore((state) => {
    const project = state.activeProjectId ? state.projects[state.activeProjectId] : null;
    const screenplay = project?.screenplay || null;
    const { sceneProgress } = state;
    if (!screenplay || screenplay.scenes.length === 0) return 0;
    
    let total = 0;
    for (const scene of screenplay.scenes) {
      const progress = sceneProgress.get(scene.sceneId);
      total += progress?.progress ?? 0;
    }
    return Math.round(total / screenplay.scenes.length);
  });
};

/**
 * Check if any scene is currently generating
 */
export const useIsGenerating = (): boolean => {
  return useDirectorStore((state) => {
    for (const progress of state.sceneProgress.values()) {
      if (progress.status === 'generating') return true;
    }
    return false;
  });
};

/**
 * Get count of completed scenes
 */
export const useCompletedScenesCount = (): number => {
  return useDirectorStore((state) => {
    let count = 0;
    for (const progress of state.sceneProgress.values()) {
      if (progress.status === 'completed') count++;
    }
    return count;
  });
};

/**
 * Get count of failed scenes
 */
export const useFailedScenesCount = (): number => {
  return useDirectorStore((state) => {
    let count = 0;
    for (const progress of state.sceneProgress.values()) {
      if (progress.status === 'failed') count++;
    }
    return count;
  });
};


